### ISSUE TITLE
Prohibited term: whitelist

### ISSUE THREAD

**Issue by cdmauney** [ibm-cloud-docs/blockchain-sw-25#1]
Do not use. Use "allowlist" instead. Use as a noun. 

https://cloud.ibm.com/docs/blockchain-sw-25?topic=blockchain-sw-25-ibp-console-import-nodes

**Comment by pamandrejko** [comment]
Fixed: https://cloud.ibm.com/docs/blockchain-sw-25?topic=blockchain-sw-25-ibp-console-import-nodes#ibp-console-import-icp
